http.host: "0.0.0.0"

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: pwlogstash_system
xpack.monitoring.elasticsearch.hosts: ["http://10.88.1.1:9200", "http://10.88.1.2:9200", "http://10.88.1.3:9200"]
xpack.monitoring.elasticsearch.sniffing: false
xpack.monitoring.collection.interval: 10s
xpack.monitoring.collection.pipeline.details.enabled: true
